on: [push, workflow_dispatch]

jobs:
  nightly-release:
    runs-on: ubuntu-latest
    name: Build release package
    steps:
    - name: Hello world action step
      id: hello
      uses: jorgenmk/test_actions@v2
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"