on:
  schedule:
    - cron:  0 21 * * 1-5
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git branch or tag to run'     
        required: true
        default: 'master'
  push:

name: Nightly build

jobs:
  build:
    strategy:
      matrix:
        target: [pca10090, pca20035]
    runs-on: ubuntu-latest
    container: 
      image:  ghcr.io/jorgenmk/build:latest
      credentials:
        username: jorgenmk
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    name: Build
    steps:
    - name: git pull
      run: |
        pwd
        cd /ncs/nrf
        git clean -xdf
        git pull
    - name: checkout branch
      if: ${{ github.events.inputs.branch != 'master' }}
      id: checkoutstage
      run: |
        cd /ncs/nrf
        git fetch origin
        git checkout ${{ github.events.inputs.branch }}
    - name: west update
      run: |
        cd /ncs
        west update
    - name: build
      id: buildstage
      run: |
        cd /
        mkdir outcomes
        python3 build-release/create_release.py ${{ matrix.target }}
        echo "::set-output name=releasepath::/`ls outcomes/*.zip`"
    - name: nightly-release
      if: ${{ github.events.inputs.branch != 'master' }}
      uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/jorgenmk/test_actions/releases/49110144/assets{?name,label}
        release_id: 49110144
        asset_path: ${{ steps.buildstage.outputs.releasepath }}
        asset_name: nightly-${{ matrix.target }}.zip
        asset_content_type: application/zip
        max_releases: 7
